apiVersion: apps/v1
kind: Deployment
metadata:
  name: menu-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: menu-app
  template:
    metadata:
      labels:
        app: menu-app
    spec:
      containers:
      - name: menu-app
        image: rookesh975/menu_card:latest 
        ports:
        - containerPort: 80
